---
apiVersion: myapp/v1
kind: Deployment
metadata:
  name: k8s-project5-1bb0788
  labels:
    app: k8s-project5-1bb0788
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-project5-1bb0788
  template:
    metadata:
      labels:
        app: k8s-project5-1bb0788
    spec:
      containers:
      - name: k8s-project5-1bb0788
        image: hieudd/myapp:latest
        ports:
          - name: k8s-project5-1bb0788
            containerPort: 3000