---
apiVersion: v1
kind: Service
metadata:
  name: k8s-project5-loadbalancer
  labels:
    app: k8s-project5-loadbalancer
spec:
  selector:
    app: myapp-project5
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000