---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project5-deployment
  labels:
    app: project5-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project5-service
  template:
    metadata:
      labels:
        app: project5-service
    spec:
      containers:
      - name: web
        image: hieudd/myapp:latest
        ports:
          - name: web
            containerPort: 3000